### ISSUE TITLE
research: research how to implement SemaphoreVerifierKeyPts contract to Soroban

### ISSUE THREAD

**Issue by evgongora** [ZencypherSolutions/semaphore-stellar-docs#1]
Resource: https://github.com/semaphore-protocol/semaphore/blob/main/packages/contracts/contracts/base/SemaphoreVerifierKeyPts.sol

**Comment by bitfalt** [comment]
Edit the `research/SemaphoreKeyPts-implementation.md` with the corresponding research. This should include the purpose of the `SemaphoreVerifierKeyPts.sol` file and an explanation of how this could be implemented in Soroban.

**Comment by petersdt** [comment]
Can I be assigned to this?

**Comment by NueloSE** [comment]
Can I handle this task?

**Comment by martinvibes** [comment]
May I take care of this?
pleAse kindly assign :)

## Research Steps:

### 1. Analyze Original Contract:

- Review SemaphoreVerifierKeyPts.sol structure
- Identify key verification methods
- Map out dependencies


### 2. Explore Soroban Requirements:

- Study Soroban's verification capabilities
- Check supported cryptographic operations
- Research memory management differences


### 3. Document Findings:

- Place in /research folder
- Include implementation recommendations
- Note any technical limitations

**Comment by anonfedora** [comment]
A full stack Blockchain developer, Will research on:

1. Identity Commitment and Proofs

2. Verifier Key Setup

3. Handling External Nullifiers and Signals

5. zk-SNARK Integration

6. State Management
