### ISSUE TITLE
[Research Docs] Issue 2: Semaphore Verifier Contract Implementation

### ISSUE THREAD

**Issue by evgongora** [ZencypherSolutions/semaphore-stellar-docs#14]
Following the compatibility and adaptation challenges with Stellar and Semaphore encountered in ZencypherSolutions/semaphore-stellar-contracts#2

Create a document with the research found inside the path`research/`

**Comment by petersdt** [comment]
I’d like to work on this.

**Comment by mayasimi** [comment]
I’d love to work on this task.

ETA <= 24hrs

**Comment by kfastov** [comment]
Hi, I have the information needed and ready to provide it in the document like requested

**Comment by Jemiiah** [comment]
Can I work on this issue I have made over 70 contributions to OD hack and made over 10 documentation to past OD Hack and I can do this effectively and quickly!! ETA 24hrs

**Comment by evgongora** [comment]
> Hi, I have the information needed and ready to provide it in the document like requested

Go ahead! @kfastov
