### ISSUE TITLE
[Research Docs] Issue 6: Integrate and leverage the Semaphore circuit into the project structure

### ISSUE THREAD

**Issue by evgongora** [ZencypherSolutions/semaphore-stellar-docs#15]
Part of Semaphore Integration is leveraging the Circuit to be compatible with Stellar, since the BLS12-381 curve is not fully compatible with Semaphore current implementation, please make a doc in the `research/` path with any relevant constraints

Related issue: ZencypherSolutions/semaphore-stellar-contracts#16

**Comment by Joe-joe25** [comment]
I’m interested in this one, would really love to work on it

**Comment by Supa-mega** [comment]
Could I take on this issue?

**Comment by mimisavage** [comment]
Could I take a shot at this?

**Comment by emarc99** [comment]
I'd like to handle this task.
ETA - 12 hours.

**Comment by khayss** [comment]
Can I take care of this issue?
