### ISSUE TITLE
docs: edit README file

### ISSUE THREAD

**Issue by bitfalt** [ZencypherSolutions/semaphore-stellar-docs#2]
Edit README file for the repo explaining that all the technical documentation and research would be in this repository. Research files must be added under the `research` folder.

Also mention that for further assistance they can join the following Telegram groups:
Semaphore-Stellar (maintainers of Semaphore Stellar): https://t.me/+-9623JNgGjEyNzI5
Semaphore Community (core developers of the Semaphore protocol): @semaphore_community (search it on Telegram)

**Comment by 0xBinayak** [comment]
@bitfalt  I am a  new contributer and have contributed to may repos i think i can make a README file  with  very easy and clear instructions.
 Time frame :under 1 Day

**Comment by PoulavBhowmick03** [comment]
Would love to tackle this!

I will update the `README.md` to clarify that this repository contains all technical documentation and research materials. I'll add a note instructing contributors to place any research files in the designated `research` folder.

Additionally, I’ll include links for further assistance, directing users to the relevant Telegram groups:
1. Semaphore-Stellar 
(https://t.me/+-9623JNgGjEyNzI5)
2. Semaphore Community (core developers of the Semaphore protocol) 

This update will ensure clear guidelines and helpful resources are readily available to everyone.

**Comment by JosueBrenes** [comment]
Hi, I'm **Josué Brenes** and I'll be working on issue.
I'm Dojo Coding member.

I estimate this will take **1 day** to complete.

**How I would resolve this**

To resolve this request, I would update the README file as follows:

1. **Include details on technical documentation and research**  
   State that all technical documentation and research files will be located in this repository. Instruct that all research files must be added under the `research` folder.

2. **Add additional support links**  
   Mention in the README that, for further assistance, users can join the following Telegram groups:

   - **Semaphore-Stellar** (maintainers of Semaphore Stellar): [https://t.me/+-9623JNgGjEyNzI5](https://t.me/+-9623JNgGjEyNzI5)
   - **Semaphore Community** (core developers of the Semaphore protocol): `@semaphore_community` (search on Telegram).

**Comment by NueloSE** [comment]
I’d like to help with this.

**Comment by josephpdf** [comment]
Hi!, my name is Joseph Poveda.
I am a student of the Systems Programming degree, I am a recent member of the Dojo Coding community, where I am getting started in the world of Web3.
I have basic knowledge of different programming languages ​​and thanks to this I hope to be able to resolve the issue.
To approach this issue, I would edit the README to clarify that all technical documentation and research will reside in this repository, with research files specifically located in the research folder. Additionally, I’d add information for contributors seeking support, guiding them to join the relevant Telegram groups, including Semaphore-Stellar for maintainer support and Semaphore Community for core developer interaction, with the provided links for direct access.

**Comment by petersdt** [comment]
Can I take this issue?

**Comment by martinvibes** [comment]
I'd be happy to do this.
kindly assign

## Issue Summary for README.md Update
#### Goal: Update the README.md to clarify the purpose and resources of the repository.

### Details:

- Explain that this repository houses all technical documentation and research files.
- Specify that research files should be located in the research folder.
- Provide links to Telegram groups for additional support:
- Semaphore-Stellar group for Semaphore Stellar maintainers: [Link](https://t.me/+-9623JNgGjEyNzI5).
- Semaphore Community for Semaphore protocol developers (search "@semaphore_community" on Telegram).

ETA 24HRS

**Comment by martinvibes** [comment]
I'd be happy to do this.
kindly assign

 Update README: Quick Steps

### 1. Add Repository Purpose:

- Main hub for technical docs & research
- All research files go in /research


### 2. Add Support Channels:

- Telegram: Semaphore-Stellar
` Link: https://t.me/+-9623JNgGjEyNzI5`

`Telegram: @semaphore_community`

**Comment by derianrddev** [comment]
Hello, I’m Derian, a software engineer focused on full-stack web development and currently part of Dojo Coding. I’d like to work on this issue.

How I would resolve the issue:

Edit the README.md file with the sections described in the issue. 
Save and upload the file to the repository.
If I have questions, I’ll ask them as soon as possible in the Telegram group. 
I will open a PR and wait for your feedback. 
Make any necessary changes according to the PR review.

**Comment by Kaminar-i** [comment]
Please, I'd like to take up this Issue

**Comment by jsandinoDev** [comment]
Hi @bitfalt I'm a full-stack developer with web3 experience member of Dojo Coding, specializing in smart contracts and decentralized applications. I've worked on projects using React, Solidity, Cairo, and blockchain tools. My skills in both front-end and back-end development allow me to build scalable and secure solutions for web3 ecosystems. I have worked on modifying the readme in projects like Shinigami & GoStarkme
I would love to work on this issue

**Comment by anonfedora** [comment]
A fullstack Blockchain developer.
    Have forked and analyzed the folder structure and understood where each element/file should be situated at.
    # First time documentation contributor

**Comment by mamicho16** [comment]
I'll update the README file to include:

Clear explanation about technical documentation location
Information about the research folder structure
Addition of the Telegram support channels
Proper formatting and organization of new content
