### ISSUE TITLE
[Research Docs] Issue 1: Research how to utilize the Snark.js for contract data

### ISSUE THREAD

**Issue by evgongora** [ZencypherSolutions/semaphore-stellar-docs#8]
References: 
https://github.com/iden3/snarkjs
https://github.com/semaphore-protocol/semaphore/blob/main/packages/contracts/contracts/base/SemaphoreVerifier.sol
https://github.com/semaphore-protocol/semaphore/blob/main/packages/contracts/contracts/base/SemaphoreVerifierKeyPts.sol

**Comment by NueloSE** [comment]
hi @evgongora kindly assign me this task. I am a technical writer and have gained some experience contributing to technical documentation for other projects over time.

**Comment by raizo07** [comment]
Could I be assigned to this? I'm a software developer with over four years of experience

**Comment by martinvibes** [comment]
May I pick this up? 
i would love to work on this issue :)

**Comment by pheobeayo** [comment]
Mind if I take this issue?

I am a web3 frontend developer skilled in technical documentation and software development. I have contributed in writting the documentation on scaffold stark. I have skills in Typescript, JavaScript, Rust, Cairo and Python.

I will tackle this issue by reading up the documentation reference shared and writing well explained documentation on how to utilize snark.js for contract data.

**Comment by 0xprivateChaos** [comment]
Hi, I'm Aman, and I can work on this issue.

Plan:

1. Analyze the provided ```SemaphoreVerifier.sol``` and ```SemaphoreVerifierKeyPts.sol```.
2. Research Snark.js outputs (verification keys, circuits) and their integration into Solidity contracts.
3. Document steps for generating and mapping Snark.js data to contracts.
4. Provide recommendations and optimizations for Snark.js integration.

**Comment by mimisavage** [comment]
I'd like to take this issue.

**Comment by josephchimebuka** [comment]
Could I be assigned to this?

**Comment by mexes20** [comment]
May I pick this up? I have three years experience in Software development and have contributed to some projects on OD here.

ETA: 10 hours.

**Comment by Tronixtek** [comment]
Please Assign this task to me I would like to do it.

**Comment by akintewe** [comment]
Can I tackle this one?

**Comment by kimcascante** [comment]
Hello! I'm Kimberly Cascante, a Dojo Coding member :) Looking for my first contribution.
I estimate this will take me around 24 to 48 hours to complete.
I will start reviewing the references, create documentation with findings, and then share.
Happy to contribute!

**Comment by MPSxDev** [comment]
I am Process Engineering, and I am fully capable of conducting an in-depth investigation. I am also committed to being available for questions at any time, going beyond merely delivering the work.

**Comment by t0fudev** [comment]
Hi! My name is t0fudev and I'm currently a computer science student and a web3 developer. I'm fully confident to work on this issue since I'm really good at doing research on any specific topic. I'm hopeful to continue contributing and make a meaningful impact to this amazing project.

Grateful for your consideration
ETA: 12 hours

**Comment by evgongora** [comment]
Hey @MPSxDev! How you doing with issue? :)

**Comment by MPSxDev** [comment]
> Hey @MPSxDev! How you doing with issue? :)

@evgongora Very well, I will soon upload the document with the information I have researched.
