### ISSUE TITLE
[Docs] Modify README to include boilerplate and SDK

### ISSUE THREAD

**Issue by bitfalt** [ZencypherSolutions/semaphore-stellar-docs#9]
Modify the `README.md` file to mention the boilerplate and SDK repository and give some context about the repositories.

Reference:
https://github.com/ZencypherSolutions/semaphore-stellar-boilerplate
https://github.com/ZencypherSolutions/semaphore-stellar-sdk

**Comment by Michaelkingsdev** [comment]
@bitfalt 
I will take my time to go through the referenced files attached to this issue and make the necessary modification in 48hrs. can this issue be assigned to me?

**Comment by kimcascante** [comment]
Hello! I'm Kimberly Cascante, a Dojo Coding member :) Looking for my first contribution.
I estimate this will take me around 24 to 48 hours to complete.
I will start reviewing the context, modify the file README.md with the information needed and share. 
Happy to contribute!

**Comment by kimcascante** [comment]
Hello! I'm Kimberly Cascante, a Dojo Coding member :) Looking for my first contribution.
I estimate this will take me around 24 to 48 hours to complete.
I will start reviewing the context, modify the file README.md with the information needed and share.
Happy to contribute!
